### ISSUE TITLE
Browser-compatible version?

### ISSUE THREAD

**Issue by bradisbell** [netnexus/node-cborwebtoken#9]
Is there any version of this repo compatible with browsers?  After building with Webpack, I get errors that the `fs` module cannot be resolved.  Is it really necessary to load files?  Are there alternative CWT modules that you know of?

```
ERROR in node_modules/cose-js/node_modules/cbor/lib/utils.js
Module not found: Error: Can't resolve 'fs' in 'node_modules\cose-js\node_modules\cbor\lib'
 @ node_modules/cose-js/node_modules/cbor/lib/utils.js 8:7-20
 @ node_modules/cose-js/node_modules/cbor/lib/diagnose.js
 @ node_modules/cose-js/node_modules/cbor/lib/cbor.js
 @ node_modules/cose-js/lib/mac.js
 @ node_modules/cose-js/lib/index.js
 @ node_modules/@netnexus/node-cborwebtoken/dist/src/index.js
```

**Comment by johannespfeiffer** [comment]
If you do it in the browser you would expose your secret to the user. 
If you just want to decode a CWT (without validating it) you could use a lib like https://github.com/paroga/cbor-js

Have a look at the code here, you just have to decode the token and then the payload again (2nd part of first decode result)

**Comment by bradisbell** [comment]
There are many use cases where generating the CWT client-side is valid.

Probably the most common case would be a client-side application generating requests against some API or service, where the client knows the secret for their particular API key.  (Think of something like the web-based AWS S3 browser.)

**Comment by johannespfeiffer** [comment]
Yes, valid point.

Unfortunately the problem is within a dependency of a dependency (namely cbor, used by our dependency cose-js) and I do not know a replacement atm.

One idea would be to create a PR for cose-js and either
(1) add a switch to cose-js, to use a plain js implementation like https://github.com/paroga/cbor-js if not in a node environment, or
(2) completely switch to a plain js implementation like cbor-js (instead of cbor)
